services:
  core-id:
    build: 
      context: ./src
      target: production
    image: core-id:prod # TODO add version number
    env_file: .env
    volumes:
    - ./logs/coreid:/usr/src/logs
    - ./config/coreid.yaml:/usr/src/config.yaml
    ports:
      - 8091:8000
    secrets:
       - jwt_signing_key
secrets:
  jwt_signing_key:
    file: ./config/jwt.pem